const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#FF1744",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#0D0D0D",
    cardForeground: "#FFFFFF",
    primary: "#FF1744",
    primaryForeground: "#FFFFFF",
    secondary: "#141414",
    secondaryForeground: "#FFFFFF",
    muted: "#111111",
    mutedForeground: "#555555",
    accent: "#FF1744",
    accentForeground: "#FFFFFF",
    destructive: "#FF1744",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E1E",
    input: "#1A1A1A",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF1744",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#0D0D0D",
    cardForeground: "#FFFFFF",
    primary: "#FF1744",
    primaryForeground: "#FFFFFF",
    secondary: "#141414",
    secondaryForeground: "#FFFFFF",
    muted: "#111111",
    mutedForeground: "#555555",
    accent: "#FF1744",
    accentForeground: "#FFFFFF",
    destructive: "#FF1744",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E1E",
    input: "#1A1A1A",
  },
  radius: 14,
};

export default colors;
